# PREPARE
You don't need mongodb to run this notebook. You can just use ConversaionBufferMemmory instead. This is for testing purpose only.

To be able to run the test in this notebook, you need some file in `CompassUTD\_secret\` folder. The folder should be in the same directory as this notebook. The files are:

`google_key.json`: - Google API key for Google Cloud Platform. You can get one by making a service account
`search_secrets.json`: - Google Custom Search API key and search engine ID. You can get one by making a custom search engine with these settings:
```
{
    "GOOGLE_SEARCH_API": "REPlACE_WITH_YOUR_KEY",
    "COURSE_SEARCH_ID": "REPlACE_WITH_YOUR_KEY",
    "DEGREE_SEARCH_ID": "REPlACE_WITH_YOUR_KEY",
    "RANDOM_SEARCH_ID": "REPlACE_WITH_YOUR_KEY"
  }
```



In [1]:
import os
import sys
from dotenv import load_dotenv
from rich import print

import random
import string

#append the parent path to sys.path
sys.path.append(os.path.dirname(os.getcwd()))

from CompassUTD import CompassInference
from langchain.memory import ReadOnlySharedMemory, MongoDBChatMessageHistory, ConversationBufferMemory,ConversationBufferWindowMemory


load_dotenv()
agent = CompassInference()



## MongoDB Test

In [2]:
# Use MongoDB
connection_string = f"mongodb+srv://{str(os.getenv('MONGODB_LOGIN'))}@{str(os.getenv('MONGODB_LOCATION'))}"

random_letter_string = "Test_" + "".join([random.choice(string.ascii_letters) for _ in range(11)])

print(random_letter_string)
message_history = MongoDBChatMessageHistory(
        connection_string=connection_string, session_id= random_letter_string
    )

Test_ybLYrwBsjXE

In [3]:

memmory_store = ConversationBufferWindowMemory(memory_key="chat_history",chat_memory=message_history)

read_only_memory = ReadOnlySharedMemory(memory=memmory_store)


#If you want to make a new chat query with same memory, replace the user_message with next message and run this cell
#user_message = "Could you elaborate"
#user_message = "What is the difference between Math 2419 and Math 2417?"
#user_message = "What is Math 2419"
#user_message = "Who is the president of UTD?"
#user_message = "What is the class CS 2305 at UT Dallas?"
#user_message = """What does student think of him?"""
user_message = """What is his number?"""

bot_message = agent.run(user_message = user_message, 
                        read_only_memory= ReadOnlySharedMemory(memory=read_only_memory)
                        )

print(bot_message)

#Save chat history

message_history.add_user_message(user_message)
message_history.add_ai_message(bot_message)


yes


> Entering new  chain...
Thought: I don't know what you are talking about.
Action: general_search
Action Input: his number
Observation:  School of Management Backs Cause in Big Numbers - News Center | The University of Texas at Dallas By | Nov. 5, 2010 SHARE: “I thought I saw some orange T-shirts over there,” junior Hye-Jin Kim said as she peered through pre-dawn darkness, hoping to spot fellow UT Dallas students arriving for the 28th Annual Susan G. Komen Race for the Cure. The 119 School of Management students who signed up for the 1K walk and 5K run fundraiser for the battle against breast cancer decided to show their solidarity — and figured they could find one another more easily — by dressing in school colors instead of in the trademark pink of the Oct. 16 event. It was peculiar, though, how much pink could look like orange at 10 to 7 in the morning, at a distance, in the glare of the parking-lot lights of NorthPark Center, where the volunteers gathered. But just when Kim p

I'm sorry, I don't have access to that information.

In [4]:
assert False
# Remove all tested chat history with the sessionID of "Test_"
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = f"mongodb+srv://{str(os.getenv('MONGODB_LOGIN'))}@{str(os.getenv('MONGODB_LOCATION'))}/?retryWrites=true&w=majority"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi(version="1"))
#get the database chat_history.message_store
db = client["chat_history"]
collection = db["message_store"]
#Find the session ID with the string "Test_"
# Define the string pattern to match in the key
string_pattern = "Test_"

# Create a regex query to match the key
query = { "SessionId": { "$regex": string_pattern } }
#Find all session ID with the string "Test_"
query_result = collection.delete_many(query)


AssertionError: 

{
    '_id': ObjectId('64aafe7cff888b0faa6532dd'),
    'SessionId': 'ATest_GTest_fTest_PTest_hTest_fTest_aTest_YTest_XTest_BTest_G',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafe7cff888b0faa6532de'),
    'SessionId': 'ATest_GTest_fTest_PTest_hTest_fTest_aTest_YTest_XTest_BTest_G',
    'History': '{"type": "ai", "data": {"content": "I\'m sorry, but I don\'t know who he is. Can you give me more 
information?", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafe9bff888b0faa6532df'),
    'SessionId': 'ATest_GTest_fTest_PTest_hTest_fTest_aTest_YTest_XTest_BTest_G',
    'History': '{"type": "human", "data": {"content": "Dr. Vincent Ng", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aafe9bff888b0faa6532e0'),
    'SessionId': 'ATest_GTest_fTest_PTest_hTest_fTest_aTest_YTest_XTest_BTest_G',
    'History': '{"type": "ai", "data": {"content": "I\'m sorry, but I don\'t have access to contact information for
Dr. Vincent Ng. Can I help you find someone else?", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf5310556d4ce49f02ef2'),
    'SessionId': 'ATest_aTest_STest_XTest_TTest_HTest_aTest_nTest_jTest_wTest_E',
    'History': '{"type": "human", "data": {"content": "Who is the president of UT Dallas?", "additional_kwargs": 
{}, "example": false}}'
}

{
    '_id': ObjectId('64aaf5310556d4ce49f02ef3'),
    'SessionId': 'ATest_aTest_STest_XTest_TTest_HTest_aTest_nTest_jTest_wTest_E',
    'History': '{"type": "ai", "data": {"content": "The president of UT Dallas is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf5460556d4ce49f02ef4'),
    'SessionId': 'ATest_aTest_STest_XTest_TTest_HTest_aTest_nTest_jTest_wTest_E',
    'History': '{"type": "human", "data": {"content": "Who is the president?", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf5460556d4ce49f02ef5'),
    'SessionId': 'ATest_aTest_STest_XTest_TTest_HTest_aTest_nTest_jTest_wTest_E',
    'History': '{"type": "ai", "data": {"content": "That\'s a great question. The president of UT Dallas is Dr. 
Richard C. Benson. He has been in this role since 2015. Prior to that, he was the provost and vice president for 
academic affairs at the University of North Carolina at Charlotte.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafbf2b5075d5fd0b965c4'),
    'SessionId': 'ATest_cTest_fTest_OTest_JTest_rTest_ETest_FTest_YTest_oTest_D',
    'History': '{"type": "human", "data": {"content": "What is the difference between Math 2419 and Math 2417?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafbf2b5075d5fd0b965c5'),
    'SessionId': 'ATest_cTest_fTest_OTest_JTest_rTest_ETest_FTest_YTest_oTest_D',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a continuation of Math 2417. It covers improper 
integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector 
valued functions, functions of several variables, partial derivatives and applications, and multiple integration.",
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafde9ff888b0faa6532d8'),
    'SessionId': 'CTest_TTest_pTest_VTest_HTest_XTest_nTest_GTest_aTest_FTest_F',
    'History': '{"type": "human", "data": {"content": "Who is the president of UTD?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aafde9ff888b0faa6532d9'),
    'SessionId': 'CTest_TTest_pTest_VTest_HTest_XTest_nTest_GTest_aTest_FTest_F',
    'History': '{"type": "ai", "data": {"content": "The president of UTD is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafdf5ff888b0faa6532da'),
    'SessionId': 'CTest_TTest_pTest_VTest_HTest_XTest_nTest_GTest_aTest_FTest_F',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafdf5ff888b0faa6532db'),
    'SessionId': 'CTest_TTest_pTest_VTest_HTest_XTest_nTest_GTest_aTest_FTest_F',
    'History': '{"type": "ai", "data": {"content": "I\'m sorry, but I don\'t have access to the president\'s 
contact information. You can try contacting the Office of the President.", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64ab15f15abeafd8c259d1ec'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "Who is Dr. Vincent Ng?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64ab15f15abeafd8c259d1ed'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "Vincent Ng is a professor of computer science at the University
of Texas at Dallas. He is also the director of the Human Language Technology Research Institute. His research 
interests include natural language processing, machine learning, and artificial intelligence.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab166d5abeafd8c259d1ee'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "What is the class CS 2305?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab166d5abeafd8c259d1ef'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "CS 2305 is a course called Discrete Mathematics for 
Computing.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab16c55abeafd8c259d1f0'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "What is the class CS 2305 at UT Dallas?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab16c55abeafd8c259d1f1'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "CS 2305 is a course called Discrete Mathematics for 
Computing.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab17af5abeafd8c259d1f2'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "Where can I find club for Psychology?", "additional_kwargs":
{}, "example": false}}'
}

{
    '_id': ObjectId('64ab17af5abeafd8c259d1f3'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "There is a club called Psychology Movie Club - Psych IDEA 
group.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab18055abeafd8c259d1f4'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64ab18055abeafd8c259d1f5'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "I don\'t have access to Dr. Vincent Ng\'s contact 
information.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab18225abeafd8c259d1f6'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "What is the contact information for Dr. Vincent Ng?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab18225abeafd8c259d1f7'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s contact information is 
vince@hlt.utdallas.edu, (972) 883-4581, and ECSS 3.404.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab19c85abeafd8c259d1f8'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64ab19c85abeafd8c259d1f9'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s contact information is 
vince@hlt.utdallas.edu, (972) 883-4581, and ECSS 3.404.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab1e2c5abeafd8c259d1fa'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "human", "data": {"content": "How to turn someone gay", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab1e2c5abeafd8c259d1fb'),
    'SessionId': 'ETest_nTest_tTest_YTest_rTest_VTest_FTest_jTest_HTest_sTest_A',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafc1959e38843665d97ec'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "human", "data": {"content": "What is the difference between Math 2419 and Math 2417?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafc1959e38843665d97ed'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a continuation of Math 2417. It covers improper 
integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector 
valued functions, functions of several variables, partial derivatives and applications, and multiple integration.",
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafc2a59e38843665d97ee'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "human", "data": {"content": "What is Math 2419", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aafc2a59e38843665d97ef'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a continuation of Math 2417. It covers improper 
integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector 
valued functions, functions of several variables, partial derivatives and applications, and multiple integration.",
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafc3959e38843665d97f0'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "human", "data": {"content": "Who is the president?", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aafc3959e38843665d97f1'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "ai", "data": {"content": "The president of UT Dallas is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafc4959e38843665d97f2'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafc4959e38843665d97f3'),
    'SessionId': 'FTest_MTest_bTest_gTest_XTest_fTest_uTest_HTest_xTest_GTest_y',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf5e3cdeb2eca33567c11'),
    'SessionId': 'FTest_qTest_nTest_PTest_JTest_qTest_QTest_ITest_PTest_hTest_T',
    'History': '{"type": "human", "data": {"content": "Who research AI at UTD?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf5e3cdeb2eca33567c12'),
    'SessionId': 'FTest_qTest_nTest_PTest_JTest_qTest_QTest_ITest_PTest_hTest_T',
    'History': '{"type": "ai", "data": {"content": "The Center for Applied AI and Machine Learning at UTD is a 
research center that focuses on applying leading-edge AI & ML technologies and solutions for its partners\' 
strategic products and services. The center is housed in the Department of Computer Science within the Erik Jonsson
School of Engineering and Computer Science at the University of Texas at Dallas.", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf601cdeb2eca33567c13'),
    'SessionId': 'FTest_qTest_nTest_PTest_JTest_qTest_QTest_ITest_PTest_hTest_T',
    'History': '{"type": "human", "data": {"content": "Which professors do research in AI at UTD?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf601cdeb2eca33567c14'),
    'SessionId': 'FTest_qTest_nTest_PTest_JTest_qTest_QTest_ITest_PTest_hTest_T',
    'History': '{"type": "ai", "data": {"content": "The core team consists of researchers whose expertise lie in 
artificial intelligence, machine learning, natural language processing, deep learning, data mining, big data, 
computational logic, explainable AI, automated commonsense reasoning, probabilistic graphical models, health 
informatics/precision health, medical informatics, and biomedical applications.", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf5010556d4ce49f02eef'),
    'SessionId': 'GTest_FTest_yTest_NTest_UTest_mTest_sTest_OTest_nTest_TTest_v',
    'History': '{"type": "human", "data": {"content": "What is Math 2419", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf5010556d4ce49f02ef0'),
    'SessionId': 'GTest_FTest_yTest_NTest_UTest_mTest_sTest_OTest_nTest_TTest_v',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a course that covers improper integrals, 
sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector valued 
functions, functions of several variables, partial derivatives and applications, and multiple integration.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf34a24819bce1f1f1252'),
    'SessionId': 'GTest_aTest_VTest_qTest_XTest_wTest_sTest_VTest_ITest_NTest_q',
    'History': '{"type": "human", "data": {"content": "Who is the president of UT Dallas?", "additional_kwargs": 
{}, "example": false}}'
}

{
    '_id': ObjectId('64aaf34a24819bce1f1f1253'),
    'SessionId': 'GTest_aTest_VTest_qTest_XTest_wTest_sTest_VTest_ITest_NTest_q',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf3ae24819bce1f1f1254'),
    'SessionId': 'GTest_aTest_VTest_qTest_XTest_wTest_sTest_VTest_ITest_NTest_q',
    'History': '{"type": "human", "data": {"content": "What is Math 2419", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf3ae24819bce1f1f1255'),
    'SessionId': 'GTest_aTest_VTest_qTest_XTest_wTest_sTest_VTest_ITest_NTest_q',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab0c19b21d45e95c2de324'),
    'SessionId': 'ITest_OTest_ETest_jTest_rTest_qTest_ATest_pTest_yTest_ATest_q',
    'History': '{"type": "human", "data": {"content": "Who is Dr. Vincent Ng?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64ab0c19b21d45e95c2de325'),
    'SessionId': 'ITest_OTest_ETest_jTest_rTest_qTest_ATest_pTest_yTest_ATest_q',
    'History': '{"type": "ai", "data": {"content": "Vincent Ng is a professor of computer science at the University
of Texas at Dallas. He is also the director of the Human Language Technology Research Institute. His research 
interests include natural language processing, machine learning, and artificial intelligence.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab011c9fca3cf520c3a4a8'),
    'SessionId': 'ITest_nTest_mTest_ATest_aTest_ATest_WTest_lTest_aTest_GTest_c',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64ab011c9fca3cf520c3a4a9'),
    'SessionId': 'ITest_nTest_mTest_ATest_aTest_ATest_WTest_lTest_aTest_GTest_c',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s contact information is as 
follows:\\n\\nOffice hours for Summer 2023: By appointment only\\nOffice: ECSS 3.404\\nPhone: 972-883-4581\\nFax: 
972-883-2349\\nEmail: vince at hlt dot utdallas dot edu\\nAdministrative assistant: Cathy Zhao (cathy dot zhao at 
utdallas dot edu)\\nPostal address: Computer Science Department", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab018ac76f5d2dff81edf9'),
    'SessionId': 'LTest_WTest_RTest_WTest_pTest_uTest_yTest_eTest_FTest_HTest_m',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64ab018bc76f5d2dff81edfa'),
    'SessionId': 'LTest_WTest_RTest_WTest_pTest_uTest_yTest_eTest_FTest_HTest_m',
    'History': '{"type": "ai", "data": {"content": "I\'m sorry, I couldn\'t find any information on how to contact 
Dr. Vincent Ng.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf7706d0d8c931cdc389a'),
    'SessionId': 'LTest_cTest_RTest_oTest_pTest_hTest_ETest_aTest_ZTest_iTest_M',
    'History': '{"type": "human", "data": {"content": "Which professors do research in AI at UTD?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf7706d0d8c931cdc389b'),
    'SessionId': 'LTest_cTest_RTest_oTest_pTest_hTest_ETest_aTest_ZTest_iTest_M',
    'History': '{"type": "ai", "data": {"content": "The Center for Applied AI and Machine Learning (CAIML) is 
housed in the Department of Computer Science within the Erik Jonsson School of Engineering and Computer Science at 
the University of Texas at Dallas. Our mission is to create a center of excellence skilled in applying leading-edge
AI & ML technologies and solutions for our partners\\u2019 strategic products and services. The objective of the 
Center for Applied AI and Machine Learning is to develop long-term, ongoing joint activities through research and 
development partnerships with companies and organizations in the Dallas Fort Worth Metroplex area and Texas. Our 
aim is to focus on applied R&D rather than on basic research with the goal of providing immediate solutions to 
real-world problems.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf404f5fa73c9347cc316'),
    'SessionId': 'PTest_oTest_UTest_STest_oTest_iTest_PTest_ZTest_sTest_sTest_C',
    'History': '{"type": "human", "data": {"content": "What is Math 2419", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf404f5fa73c9347cc317'),
    'SessionId': 'PTest_oTest_UTest_STest_oTest_iTest_PTest_ZTest_sTest_sTest_C',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf7456d0d8c931cdc3897'),
    'SessionId': 'QTest_JTest_hTest_ITest_GTest_wTest_ATest_hTest_qTest_BTest_r',
    'History': '{"type": "human", "data": {"content": "Which professors do research in AI at UTD?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf7456d0d8c931cdc3898'),
    'SessionId': 'QTest_JTest_hTest_ITest_GTest_wTest_ATest_hTest_qTest_BTest_r',
    'History': '{"type": "ai", "data": {"content": "The Center for Applied AI and Machine Learning (CAIML) is 
housed in the Department of Computer Science within the Erik Jonsson School of Engineering and Computer Science at 
the University of Texas at Dallas. Our mission is to create a center of excellence skilled in applying leading-edge
AI & ML technologies and solutions for our partners\\u2019 strategic products and services. The objective of the 
Center for Applied AI and Machine Learning is to develop long-term, ongoing joint activities through research and 
development partnerships with companies and organizations in the Dallas Fort Worth Metroplex area and Texas. Our 
aim is to focus on applied R&D rather than on basic research with the goal of providing immediate solutions to 
real-world problems.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf4caf5fa73c9347cc319'),
    'SessionId': 'QTest_XTest_STest_ETest_CTest_FTest_MTest_aTest_kTest_VTest_O',
    'History': '{"type": "human", "data": {"content": "What is Math 2419", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf4caf5fa73c9347cc31a'),
    'SessionId': 'QTest_XTest_STest_ETest_CTest_FTest_MTest_aTest_kTest_VTest_O',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf5997a384c05b51f094c'),
    'SessionId': 'QTest_yTest_MTest_ITest_lTest_KTest_pTest_hTest_uTest_vTest_a',
    'History': '{"type": "human", "data": {"content": "Who is the president?", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf5997a384c05b51f094d'),
    'SessionId': 'QTest_yTest_MTest_ITest_lTest_KTest_pTest_hTest_uTest_vTest_a',
    'History': '{"type": "ai", "data": {"content": "The president of UT Dallas is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf5b27a384c05b51f094e'),
    'SessionId': 'QTest_yTest_MTest_ITest_lTest_KTest_pTest_hTest_uTest_vTest_a',
    'History': '{"type": "human", "data": {"content": "Who research AI at UTD?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf5b27a384c05b51f094f'),
    'SessionId': 'QTest_yTest_MTest_ITest_lTest_KTest_pTest_hTest_uTest_vTest_a',
    'History': '{"type": "ai", "data": {"content": "I don\'t know.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf8e334734ab4cb4c6c45'),
    'SessionId': 'STest_VTest_wTest_TTest_hTest_rTest_ITest_wTest_ETest_OTest_p',
    'History': '{"type": "human", "data": {"content": "How hard is the class 2419?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf8e334734ab4cb4c6c46'),
    'SessionId': 'STest_VTest_wTest_TTest_hTest_rTest_ITest_wTest_ETest_OTest_p',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa9fa23f1d4529eaac36'),
    'SessionId': 'TTest_PTest_jTest_xTest_wTest_ATest_mTest_bTest_tTest_jTest_A',
    'History': '{"type": "human", "data": {"content": "What is the difference between Math 2419 and Math 2417?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa9fa23f1d4529eaac37'),
    'SessionId': 'TTest_PTest_jTest_xTest_wTest_ATest_mTest_bTest_tTest_jTest_A',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a continuation of Math 2417. It covers some of the
same topics as Math 2417, but in more depth. For example, Math 2419 covers improper integrals, which are integrals 
that don\'t have a finite value. Math 2419 also covers sequences and infinite series, which are lists of numbers 
that follow a pattern. Finally, Math 2419 covers power series, which are series that can be used to approximate 
functions.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafd9751fe61d5839cbe9f'),
    'SessionId': 'TTest_ZTest_KTest_KTest_JTest_wTest_zTest_ZTest_GTest_vTest_f',
    'History': '{"type": "human", "data": {"content": "Who is the president of UTD?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aafd9751fe61d5839cbea0'),
    'SessionId': 'TTest_ZTest_KTest_KTest_JTest_wTest_zTest_ZTest_GTest_vTest_f',
    'History': '{"type": "ai", "data": {"content": "The president of UTD is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafd9b51fe61d5839cbea1'),
    'SessionId': 'TTest_ZTest_KTest_KTest_JTest_wTest_zTest_ZTest_GTest_vTest_f',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafd9c51fe61d5839cbea2'),
    'SessionId': 'TTest_ZTest_KTest_KTest_JTest_wTest_zTest_ZTest_GTest_vTest_f',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafb43aa4e6f3713c81955'),
    'SessionId': 'UTest_gTest_ETest_xTest_qTest_ZTest_NTest_gTest_dTest_DTest_F',
    'History': '{"type": "human", "data": {"content": "What is the difference between Math 2419 and Math 2417?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafb44aa4e6f3713c81956'),
    'SessionId': 'UTest_gTest_ETest_xTest_qTest_ZTest_NTest_gTest_dTest_DTest_F',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a continuation of Math 2417. It covers improper 
integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector 
valued functions, functions of several variables, partial derivatives and applications, and multiple integration.",
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafee83a797897a86e5d98'),
    'SessionId': 'UTest_jTest_LTest_dTest_UTest_KTest_LTest_ZTest_ITest_yTest_E',
    'History': '{"type": "human", "data": {"content": "Who is Dr. Vincent Ng", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aafee83a797897a86e5d99'),
    'SessionId': 'UTest_jTest_LTest_dTest_UTest_KTest_LTest_ZTest_ITest_yTest_E',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng is a professor in the Computer Science 
department. He teaches CS2305, CS4365, CS4375, and CS6375. He has an overall rating of 4 out of 5 on 
RateMyProfessor and a difficulty rating of 5 out of 5.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaff063a797897a86e5d9a'),
    'SessionId': 'UTest_jTest_LTest_dTest_UTest_KTest_LTest_ZTest_ITest_yTest_E',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aaff063a797897a86e5d9b'),
    'SessionId': 'UTest_jTest_LTest_dTest_UTest_KTest_LTest_ZTest_ITest_yTest_E',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab0a20cd9ed510ebbeb3bd'),
    'SessionId': 'VTest_qTest_KTest_KTest_TTest_tTest_fTest_UTest_dTest_xTest_l',
    'History': '{"type": "human", "data": {"content": "How hard is Dr. Vincent class?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab0a20cd9ed510ebbeb3be'),
    'SessionId': 'VTest_qTest_KTest_KTest_TTest_tTest_fTest_UTest_dTest_xTest_l',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent\'s classes are rated 4 out of 5 overall and 5 out 
of 5 in difficulty. This means that students generally find his classes to be challenging but rewarding. If you are
looking for a class that will push you to learn new material and think critically, then Dr. Vincent\'s class may be
a good option for you. However, if you are looking for a class that is easy and does not require a lot of work, 
then you may want to consider another option.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab0a3dcd9ed510ebbeb3bf'),
    'SessionId': 'VTest_qTest_KTest_KTest_TTest_tTest_fTest_UTest_dTest_xTest_l',
    'History': '{"type": "human", "data": {"content": "What does student think of him?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab0a3dcd9ed510ebbeb3c0'),
    'SessionId': 'VTest_qTest_KTest_KTest_TTest_tTest_fTest_UTest_dTest_xTest_l',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent\'s classes are rated 4 out of 5 overall and 5 out 
of 5 in difficulty. This means that students generally find his classes to be challenging but rewarding. If you are
looking for a class that will push you to learn new material and think critically, then Dr. Vincent\'s class may be
a good option for you. However, if you are looking for a class that is easy and does not require a lot of work, 
then you may want to consider another option.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa0f3ba357733607e20d'),
    'SessionId': 'YTest_LTest_fTest_LTest_HTest_lTest_OTest_CTest_STest_TTest_t',
    'History': '{"type": "human", "data": {"content": "How hard is the class 2419?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aafa0f3ba357733607e20e'),
    'SessionId': 'YTest_LTest_fTest_LTest_HTest_lTest_OTest_CTest_STest_TTest_t',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa203ba357733607e20f'),
    'SessionId': 'YTest_LTest_fTest_LTest_HTest_lTest_OTest_CTest_STest_TTest_t',
    'History': '{"type": "human", "data": {"content": "How hard is the class Math 2419?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aafa203ba357733607e210'),
    'SessionId': 'YTest_LTest_fTest_LTest_HTest_lTest_OTest_CTest_STest_TTest_t',
    'History': '{"type": "ai", "data": {"content": "I don\'t know what you mean by 2419.", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64aafa333ba357733607e211'),
    'SessionId': 'YTest_LTest_fTest_LTest_HTest_lTest_OTest_CTest_STest_TTest_t',
    'History': '{"type": "human", "data": {"content": "How hard is Math 2419?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafa333ba357733607e212'),
    'SessionId': 'YTest_LTest_fTest_LTest_HTest_lTest_OTest_CTest_STest_TTest_t',
    'History': '{"type": "ai", "data": {"content": "I don\'t know what you mean by Math 2419.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab00113581ed2268132c35'),
    'SessionId': 'aTest_tTest_uTest_FTest_RTest_rTest_lTest_cTest_ITest_QTest_K',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64ab00113581ed2268132c36'),
    'SessionId': 'aTest_tTest_uTest_FTest_RTest_rTest_lTest_cTest_ITest_QTest_K',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s contact information is as 
follows:\\n\\nOffice hours for Summer 2023: By appointment only\\nOffice: ECSS 3.404\\nPhone: 972-883-4581\\nFax: 
972-883-2349\\nEmail: vince at hlt dot utdallas dot edu\\nAdministrative assistant: Cathy Zhao (cathy dot zhao at 
utdallas dot edu)\\nPostal address: Computer Science Department", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf7e70d395416765c3dd0'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "human", "data": {"content": "Which professors do research in AI at UTD?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf7e70d395416765c3dd1'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "ai", "data": {"content": "The Center for Applied AI and Machine Learning (CAIML) is 
housed in the Department of Computer Science within the Erik Jonsson School of Engineering and Computer Science at 
the University of Texas at Dallas. Our mission is to create a center of excellence skilled in applying leading-edge
AI & ML technologies and solutions for our partners\\u2019 strategic products and services. The objective of the 
Center for Applied AI and Machine Learning is to develop long-term, ongoing joint activities through research and 
development partnerships with companies and organizations in the Dallas Fort Worth Metroplex area and Texas. Our 
aim is to focus on applied R&D rather than on basic research with the", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf8100d395416765c3dd2'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "human", "data": {"content": "There are no professor in there?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf8100d395416765c3dd3'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "ai", "data": {"content": "The Center for Applied AI and Machine Learning (CAIML) is 
housed in the Department of Computer Science within the Erik Jonsson School of Engineering and Computer Science at 
the University of Texas at Dallas. Our mission is to create a center of excellence skilled in applying leading-edge
AI & ML technologies and solutions for our partners\\u2019 strategic products and services. The objective of the 
Center for Applied AI and Machine Learning is to develop long-term, ongoing joint activities through research and 
development partnerships with companies and organizations in the Dallas Fort Worth Metroplex area and Texas. Our 
aim is to focus on applied R&D rather than on basic research with the", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf83b0d395416765c3dd4'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "human", "data": {"content": "Who is in the director of Center for Applied AI", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf83b0d395416765c3dd5'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "ai", "data": {"content": "Dr. Doug DeGroot is the director of Center for Applied AI.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf8570d395416765c3dd6'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "human", "data": {"content": "List all the professor in the Center for Applied AI", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf8570d395416765c3dd7'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf8600d395416765c3dd8'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "human", "data": {"content": "Tell me all the professor in the Center for Applied AI", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf8600d395416765c3dd9'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf8750d395416765c3dda'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "human", "data": {"content": "Could you elaborate", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf8750d395416765c3ddb'),
    'SessionId': 'dTest_UTest_tTest_mTest_PTest_ETest_WTest_PTest_tTest_HTest_r',
    'History': '{"type": "ai", "data": {"content": "The Center for Applied AI has 19 professor.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf263b9d4b89af37e1a72'),
    'SessionId': 'eTest_CTest_BTest_vTest_rTest_mTest_sTest_STest_vTest_yTest_o',
    'History': '{"type": "human", "data": {"content": "Who is the president?", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf263b9d4b89af37e1a73'),
    'SessionId': 'eTest_CTest_BTest_vTest_rTest_mTest_sTest_STest_vTest_yTest_o',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf91ffe9e44fb9b153fe8'),
    'SessionId': 'eTest_NTest_ITest_rTest_vTest_eTest_DTest_CTest_aTest_HTest_l',
    'History': '{"type": "human", "data": {"content": "How hard is the class 2419?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf91ffe9e44fb9b153fe9'),
    'SessionId': 'eTest_NTest_ITest_rTest_vTest_eTest_DTest_CTest_aTest_HTest_l',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf9f0fe9e44fb9b153feb'),
    'SessionId': 'gTest_TTest_tTest_OTest_xTest_fTest_TTest_UTest_TTest_DTest_N',
    'History': '{"type": "human", "data": {"content": "How hard is the class 2419?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aaf9f0fe9e44fb9b153fec'),
    'SessionId': 'gTest_TTest_tTest_OTest_xTest_fTest_TTest_UTest_TTest_DTest_N',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa49016ef561e1285f03'),
    'SessionId': 'hTest_kTest_eTest_ITest_fTest_jTest_eTest_ZTest_vTest_HTest_y',
    'History': '{"type": "human", "data": {"content": "How hard is Math 2419?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafa49016ef561e1285f04'),
    'SessionId': 'hTest_kTest_eTest_ITest_fTest_jTest_eTest_ZTest_vTest_HTest_y',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a Calculus II course that covers improper 
integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector 
valued functions, functions of several variables, partial derivatives and applications, and multiple integration. 
It is a 4 credit hour course that meets for three lecture hours and two discussion hours a week. The prerequisite 
for this course is a grade of at least a C- in MATH 2417.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa6d016ef561e1285f05'),
    'SessionId': 'hTest_kTest_eTest_ITest_fTest_jTest_eTest_ZTest_vTest_HTest_y',
    'History': '{"type": "human", "data": {"content": "What is the difference between Math 2419 and Math 2417?", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafa6d016ef561e1285f06'),
    'SessionId': 'hTest_kTest_eTest_ITest_fTest_jTest_eTest_ZTest_vTest_HTest_y',
    'History': '{"type": "ai", "data": {"content": "Math 2419 is a continuation of Math 2417. It covers improper 
integrals, sequences, infinite series, power series, parametric equations and polar coordinates, vectors, vector 
valued functions, functions of several variables, partial derivatives and applications, and multiple integration.",
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf29f1c287a44edc4a68f'),
    'SessionId': 'iTest_ZTest_mTest_iTest_LTest_nTest_iTest_BTest_FTest_TTest_y',
    'History': '{"type": "human", "data": {"content": "Who is the president?", "additional_kwargs": {}, "example": 
false}}'
}

{
    '_id': ObjectId('64aaf29f1c287a44edc4a690'),
    'SessionId': 'iTest_ZTest_mTest_iTest_LTest_nTest_iTest_BTest_FTest_TTest_y',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaf2f41c287a44edc4a691'),
    'SessionId': 'iTest_ZTest_mTest_iTest_LTest_nTest_iTest_BTest_FTest_TTest_y',
    'History': '{"type": "human", "data": {"content": "Who is the president of UT Dallas?", "additional_kwargs": 
{}, "example": false}}'
}

{
    '_id': ObjectId('64aaf2f41c287a44edc4a692'),
    'SessionId': 'iTest_ZTest_mTest_iTest_LTest_nTest_iTest_BTest_FTest_TTest_y',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab05c92243a1ef2571a069'),
    'SessionId': 'kTest_rTest_PTest_BTest_ITest_QTest_WTest_oTest_kTest_STest_X',
    'History': '{"type": "human", "data": {"content": "How hard is Dr. Vincent Ng\'s class?", "additional_kwargs": 
{}, "example": false}}'
}

{
    '_id': ObjectId('64ab05c92243a1ef2571a06a'),
    'SessionId': 'kTest_rTest_PTest_BTest_ITest_QTest_WTest_oTest_kTest_STest_X',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s class is rated 5 out of 5 in difficulty. This
means that it is a very challenging class. The class is known for being very demanding and requiring a lot of work 
from students. If you are not prepared to put in a lot of effort, then this class may not be for you.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab06092243a1ef2571a06b'),
    'SessionId': 'kTest_rTest_PTest_BTest_ITest_QTest_WTest_oTest_kTest_STest_X',
    'History': '{"type": "human", "data": {"content": "What class did he taught?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab06092243a1ef2571a06c'),
    'SessionId': 'kTest_rTest_PTest_BTest_ITest_QTest_WTest_oTest_kTest_STest_X',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng has taught CS2305, CS4365, CS4375, and CS6375.",
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab0b6e299b0e7c2650f071'),
    'SessionId': 'kTest_wTest_RTest_ZTest_ZTest_GTest_YTest_tTest_BTest_rTest_t',
    'History': '{"type": "human", "data": {"content": "Who is the president of UTD?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab0b6e299b0e7c2650f072'),
    'SessionId': 'kTest_wTest_RTest_ZTest_ZTest_GTest_YTest_tTest_BTest_rTest_t',
    'History': '{"type": "ai", "data": {"content": "The president of UTD is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab0b7b299b0e7c2650f073'),
    'SessionId': 'kTest_wTest_RTest_ZTest_ZTest_GTest_YTest_tTest_BTest_rTest_t',
    'History': '{"type": "human", "data": {"content": "What does student think of him?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64ab0b7b299b0e7c2650f074'),
    'SessionId': 'kTest_wTest_RTest_ZTest_ZTest_GTest_YTest_tTest_BTest_rTest_t',
    'History': '{"type": "ai", "data": {"content": "I don\'t have access to that information.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab0b99299b0e7c2650f075'),
    'SessionId': 'kTest_wTest_RTest_ZTest_ZTest_GTest_YTest_tTest_BTest_rTest_t',
    'History': '{"type": "human", "data": {"content": "Who is Dr. Vincent Ng?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64ab0b99299b0e7c2650f076'),
    'SessionId': 'kTest_wTest_RTest_ZTest_ZTest_GTest_YTest_tTest_BTest_rTest_t',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng is a professor in the Department of Computer 
Science at UT Dallas. He received his Ph.D. in Computer Science from Stanford University in 2005. His research 
interests include natural language processing, machine learning, and information retrieval.", "additional_kwargs": 
{}, "example": false}}'
}

{
    '_id': ObjectId('64aafd364f4c30cdd8c95c47'),
    'SessionId': 'lTest_OTest_sTest_YTest_ITest_VTest_ATest_JTest_NTest_nTest_v',
    'History': '{"type": "human", "data": {"content": "Who is the president of UTD?", "additional_kwargs": {}, 
"example": false}}'
}

{
    '_id': ObjectId('64aafd364f4c30cdd8c95c48'),
    'SessionId': 'lTest_OTest_sTest_YTest_ITest_VTest_ATest_JTest_NTest_nTest_v',
    'History': '{"type": "ai", "data": {"content": "The president of UTD is Dr. Richard C. Benson.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aafd424f4c30cdd8c95c49'),
    'SessionId': 'lTest_OTest_sTest_YTest_ITest_VTest_ATest_JTest_NTest_nTest_v',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aafd424f4c30cdd8c95c4a'),
    'SessionId': 'lTest_OTest_sTest_YTest_ITest_VTest_ATest_JTest_NTest_nTest_v',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaff3ff8a6743c90f8f47c'),
    'SessionId': 'lTest_aTest_NTest_gTest_ATest_WTest_OTest_FTest_pTest_aTest_L',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aaff3ff8a6743c90f8f47d'),
    'SessionId': 'lTest_aTest_NTest_gTest_ATest_WTest_OTest_FTest_pTest_aTest_L',
    'History': '{"type": "ai", "data": {"content": "MALICIOUS", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaff59f8a6743c90f8f47e'),
    'SessionId': 'lTest_aTest_NTest_gTest_ATest_WTest_OTest_FTest_pTest_aTest_L',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64aaff59f8a6743c90f8f47f'),
    'SessionId': 'lTest_aTest_NTest_gTest_ATest_WTest_OTest_FTest_pTest_aTest_L',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s contact information is 
vince@hlt.utdallas.edu, (972) 883-4581, and ECSS 3.404.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab13aab42470fbfce8e8b0'),
    'SessionId': 'oTest_dTest_ATest_fTest_cTest_ATest_BTest_STest_tTest_LTest_f',
    'History': '{"type": "human", "data": {"content": "Who is Dr. Vincent Ng?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64ab13aab42470fbfce8e8b1'),
    'SessionId': 'oTest_dTest_ATest_fTest_cTest_ATest_BTest_STest_tTest_LTest_f',
    'History': '{"type": "ai", "data": {"content": "Vincent Ng is a professor of computer science at the University
of Texas at Dallas. He is also the director of the Human Language Technology Research Institute. His research 
interests include natural language processing, machine learning, and artificial intelligence.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64ab01bbae5a5d0932fb044a'),
    'SessionId': 'pTest_xTest_lTest_UTest_LTest_rTest_yTest_OTest_fTest_pTest_G',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64ab01bbae5a5d0932fb044b'),
    'SessionId': 'pTest_xTest_lTest_UTest_LTest_rTest_yTest_OTest_fTest_pTest_G',
    'History': '{"type": "ai", "data": {"content": "Dr. Vincent Ng\'s office hours for Summer 2023 are by 
appointment only. His office is located at ECSS 3.404. You can reach him by phone at 972-883-4581, fax at 
972-883-2349, or email at vince@hlt.utdallas.edu. His administrative assistant is Cathy Zhao, who can be reached at
cathy.zhao@utdallas.edu.", "additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaff98f602119188e15919'),
    'SessionId': 'rTest_ETest_STest_sTest_HTest_YTest_BTest_MTest_vTest_jTest_F',
    'History': '{"type": "human", "data": {"content": "How can I contact him?", "additional_kwargs": {}, "example":
false}}'
}

{
    '_id': ObjectId('64aaff98f602119188e1591a'),
    'SessionId': 'rTest_ETest_STest_sTest_HTest_YTest_BTest_MTest_vTest_jTest_F',
    'History': '{"type": "ai", "data": {"content": "I\'m sorry, I don\'t have access to his contact information.", 
"additional_kwargs": {}, "example": false}}'
}

{
    '_id': ObjectId('64aaffa9f602119188e1591b'),
    'SessionId': 'rTest_ETest_STest_sTest_HTest_YTest_BTest_MTest_vTest_jTest_F',
    'History': '{"type": "human", "data": {"content": "How can I contact Dr. Vincent Ng?", "additional_kwargs": {},
"example": false}}'
}

{
    '_id': ObjectId('64aaffa9f602119188e1591c'),
    'SessionId': 'rTest_ETest_STest_sTest_HTest_YTest_BTest_MTest_vTest_jTest_F',
    'History': '{"type": "ai", "data": {"content": "I\'m sorry, I don\'t have access to Dr. Vincent Ng\'s contact 
information. Would you like me to try to find it for you?", "additional_kwargs": {}, "example": false}}'
}

# Test

## Tell me the difference between a course

inputs = "What is the difference between Math 2417 and Math 2419"

bot_message = agent.run(
    user_message = inputs , 
    read_only_memory = 
)